Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 60
Metrics/ClassLength:
  Max: 600

Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
