# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_15; end
module ::Anonymous_Delegator_16; end
module ::Anonymous_Delegator_17; end
module ::Anonymous_Delegator_18; end
module ::Anonymous_Delegator_20; end
module ::Anonymous_Delegator_4; end
module ::Anonymous_Delegator_5; end
module ActiveSupport::ActionController::Base; end
module ActiveSupport::StringInquirer; end
