# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_11; end
module ::Anonymous_Delegator_20; end
module ::Anonymous_Delegator_21; end
module ::Anonymous_Delegator_22; end
module ::Anonymous_Delegator_23; end
module ActiveSupport::ActionController::Base; end
module ActiveSupport::StringInquirer; end
